version: "3.9"
services:
  pgdatabase:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  jupyter:
    build: .
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    depends_on:
      - pgdatabase
