
services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: papis.mballo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pispa
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebook:/ny_taxi/work
      - ./data:/data
    depends_on:
      - db
    environment:
      JUPYTER_TOKEN: "secret"

volumes:
  postgres_data:
  pgadmin_data:
