version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebook:/ny_taxi/work
      - ./data:/data
    depends_on:
      - postgres
    environment:
      JUPYTER_TOKEN: "secret"

volumes:
  pg_data:
